package com.xcy.mybatis.mo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GeneratorCardTaskInfoMoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public GeneratorCardTaskInfoMoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDisplayIdIsNull() {
            addCriterion("display_id is null");
            return (Criteria) this;
        }

        public Criteria andDisplayIdIsNotNull() {
            addCriterion("display_id is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayIdEqualTo(String value) {
            addCriterion("display_id =", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdNotEqualTo(String value) {
            addCriterion("display_id <>", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdGreaterThan(String value) {
            addCriterion("display_id >", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdGreaterThanOrEqualTo(String value) {
            addCriterion("display_id >=", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdLessThan(String value) {
            addCriterion("display_id <", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdLessThanOrEqualTo(String value) {
            addCriterion("display_id <=", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdLike(String value) {
            addCriterion("display_id like", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdNotLike(String value) {
            addCriterion("display_id not like", value, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdIn(List<String> values) {
            addCriterion("display_id in", values, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdNotIn(List<String> values) {
            addCriterion("display_id not in", values, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdBetween(String value1, String value2) {
            addCriterion("display_id between", value1, value2, "displayId");
            return (Criteria) this;
        }

        public Criteria andDisplayIdNotBetween(String value1, String value2) {
            addCriterion("display_id not between", value1, value2, "displayId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeIsNull() {
            addCriterion("generator_type is null");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeIsNotNull() {
            addCriterion("generator_type is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeEqualTo(Integer value) {
            addCriterion("generator_type =", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeNotEqualTo(Integer value) {
            addCriterion("generator_type <>", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeGreaterThan(Integer value) {
            addCriterion("generator_type >", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("generator_type >=", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeLessThan(Integer value) {
            addCriterion("generator_type <", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeLessThanOrEqualTo(Integer value) {
            addCriterion("generator_type <=", value, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeIn(List<Integer> values) {
            addCriterion("generator_type in", values, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeNotIn(List<Integer> values) {
            addCriterion("generator_type not in", values, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeBetween(Integer value1, Integer value2) {
            addCriterion("generator_type between", value1, value2, "generatorType");
            return (Criteria) this;
        }

        public Criteria andGeneratorTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("generator_type not between", value1, value2, "generatorType");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Long value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Long value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Long value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Long value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Long value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Long> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Long> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Long value1, Long value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Long value1, Long value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIsNull() {
            addCriterion("operator_name is null");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIsNotNull() {
            addCriterion("operator_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorNameEqualTo(String value) {
            addCriterion("operator_name =", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotEqualTo(String value) {
            addCriterion("operator_name <>", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameGreaterThan(String value) {
            addCriterion("operator_name >", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_name >=", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLessThan(String value) {
            addCriterion("operator_name <", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLessThanOrEqualTo(String value) {
            addCriterion("operator_name <=", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLike(String value) {
            addCriterion("operator_name like", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotLike(String value) {
            addCriterion("operator_name not like", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIn(List<String> values) {
            addCriterion("operator_name in", values, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotIn(List<String> values) {
            addCriterion("operator_name not in", values, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameBetween(String value1, String value2) {
            addCriterion("operator_name between", value1, value2, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotBetween(String value1, String value2) {
            addCriterion("operator_name not between", value1, value2, "operatorName");
            return (Criteria) this;
        }

        public Criteria andSendTargetIsNull() {
            addCriterion("send_target is null");
            return (Criteria) this;
        }

        public Criteria andSendTargetIsNotNull() {
            addCriterion("send_target is not null");
            return (Criteria) this;
        }

        public Criteria andSendTargetEqualTo(Integer value) {
            addCriterion("send_target =", value, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetNotEqualTo(Integer value) {
            addCriterion("send_target <>", value, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetGreaterThan(Integer value) {
            addCriterion("send_target >", value, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetGreaterThanOrEqualTo(Integer value) {
            addCriterion("send_target >=", value, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetLessThan(Integer value) {
            addCriterion("send_target <", value, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetLessThanOrEqualTo(Integer value) {
            addCriterion("send_target <=", value, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetIn(List<Integer> values) {
            addCriterion("send_target in", values, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetNotIn(List<Integer> values) {
            addCriterion("send_target not in", values, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetBetween(Integer value1, Integer value2) {
            addCriterion("send_target between", value1, value2, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendTargetNotBetween(Integer value1, Integer value2) {
            addCriterion("send_target not between", value1, value2, "sendTarget");
            return (Criteria) this;
        }

        public Criteria andSendProgressIsNull() {
            addCriterion("send_progress is null");
            return (Criteria) this;
        }

        public Criteria andSendProgressIsNotNull() {
            addCriterion("send_progress is not null");
            return (Criteria) this;
        }

        public Criteria andSendProgressEqualTo(Integer value) {
            addCriterion("send_progress =", value, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressNotEqualTo(Integer value) {
            addCriterion("send_progress <>", value, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressGreaterThan(Integer value) {
            addCriterion("send_progress >", value, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressGreaterThanOrEqualTo(Integer value) {
            addCriterion("send_progress >=", value, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressLessThan(Integer value) {
            addCriterion("send_progress <", value, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressLessThanOrEqualTo(Integer value) {
            addCriterion("send_progress <=", value, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressIn(List<Integer> values) {
            addCriterion("send_progress in", values, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressNotIn(List<Integer> values) {
            addCriterion("send_progress not in", values, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressBetween(Integer value1, Integer value2) {
            addCriterion("send_progress between", value1, value2, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendProgressNotBetween(Integer value1, Integer value2) {
            addCriterion("send_progress not between", value1, value2, "sendProgress");
            return (Criteria) this;
        }

        public Criteria andSendStatusIsNull() {
            addCriterion("send_status is null");
            return (Criteria) this;
        }

        public Criteria andSendStatusIsNotNull() {
            addCriterion("send_status is not null");
            return (Criteria) this;
        }

        public Criteria andSendStatusEqualTo(Integer value) {
            addCriterion("send_status =", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotEqualTo(Integer value) {
            addCriterion("send_status <>", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusGreaterThan(Integer value) {
            addCriterion("send_status >", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("send_status >=", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusLessThan(Integer value) {
            addCriterion("send_status <", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusLessThanOrEqualTo(Integer value) {
            addCriterion("send_status <=", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusIn(List<Integer> values) {
            addCriterion("send_status in", values, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotIn(List<Integer> values) {
            addCriterion("send_status not in", values, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusBetween(Integer value1, Integer value2) {
            addCriterion("send_status between", value1, value2, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("send_status not between", value1, value2, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusIsNull() {
            addCriterion("generator_status is null");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusIsNotNull() {
            addCriterion("generator_status is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusEqualTo(Integer value) {
            addCriterion("generator_status =", value, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusNotEqualTo(Integer value) {
            addCriterion("generator_status <>", value, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusGreaterThan(Integer value) {
            addCriterion("generator_status >", value, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("generator_status >=", value, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusLessThan(Integer value) {
            addCriterion("generator_status <", value, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusLessThanOrEqualTo(Integer value) {
            addCriterion("generator_status <=", value, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusIn(List<Integer> values) {
            addCriterion("generator_status in", values, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusNotIn(List<Integer> values) {
            addCriterion("generator_status not in", values, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusBetween(Integer value1, Integer value2) {
            addCriterion("generator_status between", value1, value2, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("generator_status not between", value1, value2, "generatorStatus");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeIsNull() {
            addCriterion("generator_fail_code is null");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeIsNotNull() {
            addCriterion("generator_fail_code is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeEqualTo(String value) {
            addCriterion("generator_fail_code =", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeNotEqualTo(String value) {
            addCriterion("generator_fail_code <>", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeGreaterThan(String value) {
            addCriterion("generator_fail_code >", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeGreaterThanOrEqualTo(String value) {
            addCriterion("generator_fail_code >=", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeLessThan(String value) {
            addCriterion("generator_fail_code <", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeLessThanOrEqualTo(String value) {
            addCriterion("generator_fail_code <=", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeLike(String value) {
            addCriterion("generator_fail_code like", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeNotLike(String value) {
            addCriterion("generator_fail_code not like", value, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeIn(List<String> values) {
            addCriterion("generator_fail_code in", values, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeNotIn(List<String> values) {
            addCriterion("generator_fail_code not in", values, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeBetween(String value1, String value2) {
            addCriterion("generator_fail_code between", value1, value2, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailCodeNotBetween(String value1, String value2) {
            addCriterion("generator_fail_code not between", value1, value2, "generatorFailCode");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageIsNull() {
            addCriterion("generator_fail_message is null");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageIsNotNull() {
            addCriterion("generator_fail_message is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageEqualTo(String value) {
            addCriterion("generator_fail_message =", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageNotEqualTo(String value) {
            addCriterion("generator_fail_message <>", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageGreaterThan(String value) {
            addCriterion("generator_fail_message >", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageGreaterThanOrEqualTo(String value) {
            addCriterion("generator_fail_message >=", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageLessThan(String value) {
            addCriterion("generator_fail_message <", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageLessThanOrEqualTo(String value) {
            addCriterion("generator_fail_message <=", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageLike(String value) {
            addCriterion("generator_fail_message like", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageNotLike(String value) {
            addCriterion("generator_fail_message not like", value, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageIn(List<String> values) {
            addCriterion("generator_fail_message in", values, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageNotIn(List<String> values) {
            addCriterion("generator_fail_message not in", values, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageBetween(String value1, String value2) {
            addCriterion("generator_fail_message between", value1, value2, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andGeneratorFailMessageNotBetween(String value1, String value2) {
            addCriterion("generator_fail_message not between", value1, value2, "generatorFailMessage");
            return (Criteria) this;
        }

        public Criteria andFileLengthIsNull() {
            addCriterion("file_length is null");
            return (Criteria) this;
        }

        public Criteria andFileLengthIsNotNull() {
            addCriterion("file_length is not null");
            return (Criteria) this;
        }

        public Criteria andFileLengthEqualTo(Integer value) {
            addCriterion("file_length =", value, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthNotEqualTo(Integer value) {
            addCriterion("file_length <>", value, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthGreaterThan(Integer value) {
            addCriterion("file_length >", value, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("file_length >=", value, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthLessThan(Integer value) {
            addCriterion("file_length <", value, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthLessThanOrEqualTo(Integer value) {
            addCriterion("file_length <=", value, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthIn(List<Integer> values) {
            addCriterion("file_length in", values, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthNotIn(List<Integer> values) {
            addCriterion("file_length not in", values, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthBetween(Integer value1, Integer value2) {
            addCriterion("file_length between", value1, value2, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("file_length not between", value1, value2, "fileLength");
            return (Criteria) this;
        }

        public Criteria andFileSavePathIsNull() {
            addCriterion("file_save_path is null");
            return (Criteria) this;
        }

        public Criteria andFileSavePathIsNotNull() {
            addCriterion("file_save_path is not null");
            return (Criteria) this;
        }

        public Criteria andFileSavePathEqualTo(String value) {
            addCriterion("file_save_path =", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathNotEqualTo(String value) {
            addCriterion("file_save_path <>", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathGreaterThan(String value) {
            addCriterion("file_save_path >", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathGreaterThanOrEqualTo(String value) {
            addCriterion("file_save_path >=", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathLessThan(String value) {
            addCriterion("file_save_path <", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathLessThanOrEqualTo(String value) {
            addCriterion("file_save_path <=", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathLike(String value) {
            addCriterion("file_save_path like", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathNotLike(String value) {
            addCriterion("file_save_path not like", value, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathIn(List<String> values) {
            addCriterion("file_save_path in", values, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathNotIn(List<String> values) {
            addCriterion("file_save_path not in", values, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathBetween(String value1, String value2) {
            addCriterion("file_save_path between", value1, value2, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andFileSavePathNotBetween(String value1, String value2) {
            addCriterion("file_save_path not between", value1, value2, "fileSavePath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathIsNull() {
            addCriterion("test_paper_path is null");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathIsNotNull() {
            addCriterion("test_paper_path is not null");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathEqualTo(String value) {
            addCriterion("test_paper_path =", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathNotEqualTo(String value) {
            addCriterion("test_paper_path <>", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathGreaterThan(String value) {
            addCriterion("test_paper_path >", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathGreaterThanOrEqualTo(String value) {
            addCriterion("test_paper_path >=", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathLessThan(String value) {
            addCriterion("test_paper_path <", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathLessThanOrEqualTo(String value) {
            addCriterion("test_paper_path <=", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathLike(String value) {
            addCriterion("test_paper_path like", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathNotLike(String value) {
            addCriterion("test_paper_path not like", value, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathIn(List<String> values) {
            addCriterion("test_paper_path in", values, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathNotIn(List<String> values) {
            addCriterion("test_paper_path not in", values, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathBetween(String value1, String value2) {
            addCriterion("test_paper_path between", value1, value2, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperPathNotBetween(String value1, String value2) {
            addCriterion("test_paper_path not between", value1, value2, "testPaperPath");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeIsNull() {
            addCriterion("need_paste_code is null");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeIsNotNull() {
            addCriterion("need_paste_code is not null");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeEqualTo(Boolean value) {
            addCriterion("need_paste_code =", value, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeNotEqualTo(Boolean value) {
            addCriterion("need_paste_code <>", value, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeGreaterThan(Boolean value) {
            addCriterion("need_paste_code >", value, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("need_paste_code >=", value, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeLessThan(Boolean value) {
            addCriterion("need_paste_code <", value, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeLessThanOrEqualTo(Boolean value) {
            addCriterion("need_paste_code <=", value, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeIn(List<Boolean> values) {
            addCriterion("need_paste_code in", values, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeNotIn(List<Boolean> values) {
            addCriterion("need_paste_code not in", values, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeBetween(Boolean value1, Boolean value2) {
            addCriterion("need_paste_code between", value1, value2, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andNeedPasteCodeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("need_paste_code not between", value1, value2, "needPasteCode");
            return (Criteria) this;
        }

        public Criteria andStudentCountIsNull() {
            addCriterion("student_count is null");
            return (Criteria) this;
        }

        public Criteria andStudentCountIsNotNull() {
            addCriterion("student_count is not null");
            return (Criteria) this;
        }

        public Criteria andStudentCountEqualTo(Integer value) {
            addCriterion("student_count =", value, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountNotEqualTo(Integer value) {
            addCriterion("student_count <>", value, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountGreaterThan(Integer value) {
            addCriterion("student_count >", value, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_count >=", value, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountLessThan(Integer value) {
            addCriterion("student_count <", value, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountLessThanOrEqualTo(Integer value) {
            addCriterion("student_count <=", value, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountIn(List<Integer> values) {
            addCriterion("student_count in", values, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountNotIn(List<Integer> values) {
            addCriterion("student_count not in", values, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountBetween(Integer value1, Integer value2) {
            addCriterion("student_count between", value1, value2, "studentCount");
            return (Criteria) this;
        }

        public Criteria andStudentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("student_count not between", value1, value2, "studentCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountIsNull() {
            addCriterion("unfinished_count is null");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountIsNotNull() {
            addCriterion("unfinished_count is not null");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountEqualTo(Integer value) {
            addCriterion("unfinished_count =", value, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountNotEqualTo(Integer value) {
            addCriterion("unfinished_count <>", value, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountGreaterThan(Integer value) {
            addCriterion("unfinished_count >", value, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("unfinished_count >=", value, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountLessThan(Integer value) {
            addCriterion("unfinished_count <", value, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountLessThanOrEqualTo(Integer value) {
            addCriterion("unfinished_count <=", value, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountIn(List<Integer> values) {
            addCriterion("unfinished_count in", values, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountNotIn(List<Integer> values) {
            addCriterion("unfinished_count not in", values, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountBetween(Integer value1, Integer value2) {
            addCriterion("unfinished_count between", value1, value2, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andUnfinishedCountNotBetween(Integer value1, Integer value2) {
            addCriterion("unfinished_count not between", value1, value2, "unfinishedCount");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("send_time is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("send_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(Date value) {
            addCriterion("send_time =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(Date value) {
            addCriterion("send_time <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(Date value) {
            addCriterion("send_time >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("send_time >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(Date value) {
            addCriterion("send_time <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("send_time <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<Date> values) {
            addCriterion("send_time in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<Date> values) {
            addCriterion("send_time not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(Date value1, Date value2) {
            addCriterion("send_time between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("send_time not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andPrintOrderIsNull() {
            addCriterion("print_order is null");
            return (Criteria) this;
        }

        public Criteria andPrintOrderIsNotNull() {
            addCriterion("print_order is not null");
            return (Criteria) this;
        }

        public Criteria andPrintOrderEqualTo(Integer value) {
            addCriterion("print_order =", value, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderNotEqualTo(Integer value) {
            addCriterion("print_order <>", value, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderGreaterThan(Integer value) {
            addCriterion("print_order >", value, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("print_order >=", value, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderLessThan(Integer value) {
            addCriterion("print_order <", value, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderLessThanOrEqualTo(Integer value) {
            addCriterion("print_order <=", value, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderIn(List<Integer> values) {
            addCriterion("print_order in", values, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderNotIn(List<Integer> values) {
            addCriterion("print_order not in", values, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderBetween(Integer value1, Integer value2) {
            addCriterion("print_order between", value1, value2, "printOrder");
            return (Criteria) this;
        }

        public Criteria andPrintOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("print_order not between", value1, value2, "printOrder");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperIsNull() {
            addCriterion("need_teacher_paper is null");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperIsNotNull() {
            addCriterion("need_teacher_paper is not null");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperEqualTo(Boolean value) {
            addCriterion("need_teacher_paper =", value, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperNotEqualTo(Boolean value) {
            addCriterion("need_teacher_paper <>", value, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperGreaterThan(Boolean value) {
            addCriterion("need_teacher_paper >", value, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperGreaterThanOrEqualTo(Boolean value) {
            addCriterion("need_teacher_paper >=", value, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperLessThan(Boolean value) {
            addCriterion("need_teacher_paper <", value, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperLessThanOrEqualTo(Boolean value) {
            addCriterion("need_teacher_paper <=", value, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperIn(List<Boolean> values) {
            addCriterion("need_teacher_paper in", values, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperNotIn(List<Boolean> values) {
            addCriterion("need_teacher_paper not in", values, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperBetween(Boolean value1, Boolean value2) {
            addCriterion("need_teacher_paper between", value1, value2, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andNeedTeacherPaperNotBetween(Boolean value1, Boolean value2) {
            addCriterion("need_teacher_paper not between", value1, value2, "needTeacherPaper");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathIsNull() {
            addCriterion("original_paper_path is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathIsNotNull() {
            addCriterion("original_paper_path is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathEqualTo(String value) {
            addCriterion("original_paper_path =", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathNotEqualTo(String value) {
            addCriterion("original_paper_path <>", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathGreaterThan(String value) {
            addCriterion("original_paper_path >", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathGreaterThanOrEqualTo(String value) {
            addCriterion("original_paper_path >=", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathLessThan(String value) {
            addCriterion("original_paper_path <", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathLessThanOrEqualTo(String value) {
            addCriterion("original_paper_path <=", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathLike(String value) {
            addCriterion("original_paper_path like", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathNotLike(String value) {
            addCriterion("original_paper_path not like", value, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathIn(List<String> values) {
            addCriterion("original_paper_path in", values, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathNotIn(List<String> values) {
            addCriterion("original_paper_path not in", values, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathBetween(String value1, String value2) {
            addCriterion("original_paper_path between", value1, value2, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andOriginalPaperPathNotBetween(String value1, String value2) {
            addCriterion("original_paper_path not between", value1, value2, "originalPaperPath");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleIsNull() {
            addCriterion("test_paper_style is null");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleIsNotNull() {
            addCriterion("test_paper_style is not null");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleEqualTo(Integer value) {
            addCriterion("test_paper_style =", value, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleNotEqualTo(Integer value) {
            addCriterion("test_paper_style <>", value, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleGreaterThan(Integer value) {
            addCriterion("test_paper_style >", value, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_paper_style >=", value, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleLessThan(Integer value) {
            addCriterion("test_paper_style <", value, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleLessThanOrEqualTo(Integer value) {
            addCriterion("test_paper_style <=", value, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleIn(List<Integer> values) {
            addCriterion("test_paper_style in", values, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleNotIn(List<Integer> values) {
            addCriterion("test_paper_style not in", values, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleBetween(Integer value1, Integer value2) {
            addCriterion("test_paper_style between", value1, value2, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTestPaperStyleNotBetween(Integer value1, Integer value2) {
            addCriterion("test_paper_style not between", value1, value2, "testPaperStyle");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathIsNull() {
            addCriterion("teacher_paper_path is null");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathIsNotNull() {
            addCriterion("teacher_paper_path is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathEqualTo(String value) {
            addCriterion("teacher_paper_path =", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathNotEqualTo(String value) {
            addCriterion("teacher_paper_path <>", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathGreaterThan(String value) {
            addCriterion("teacher_paper_path >", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_paper_path >=", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathLessThan(String value) {
            addCriterion("teacher_paper_path <", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathLessThanOrEqualTo(String value) {
            addCriterion("teacher_paper_path <=", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathLike(String value) {
            addCriterion("teacher_paper_path like", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathNotLike(String value) {
            addCriterion("teacher_paper_path not like", value, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathIn(List<String> values) {
            addCriterion("teacher_paper_path in", values, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathNotIn(List<String> values) {
            addCriterion("teacher_paper_path not in", values, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathBetween(String value1, String value2) {
            addCriterion("teacher_paper_path between", value1, value2, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPathNotBetween(String value1, String value2) {
            addCriterion("teacher_paper_path not between", value1, value2, "teacherPaperPath");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageIsNull() {
            addCriterion("answercard_page is null");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageIsNotNull() {
            addCriterion("answercard_page is not null");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageEqualTo(Integer value) {
            addCriterion("answercard_page =", value, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageNotEqualTo(Integer value) {
            addCriterion("answercard_page <>", value, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageGreaterThan(Integer value) {
            addCriterion("answercard_page >", value, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageGreaterThanOrEqualTo(Integer value) {
            addCriterion("answercard_page >=", value, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageLessThan(Integer value) {
            addCriterion("answercard_page <", value, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageLessThanOrEqualTo(Integer value) {
            addCriterion("answercard_page <=", value, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageIn(List<Integer> values) {
            addCriterion("answercard_page in", values, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageNotIn(List<Integer> values) {
            addCriterion("answercard_page not in", values, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageBetween(Integer value1, Integer value2) {
            addCriterion("answercard_page between", value1, value2, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andAnswercardPageNotBetween(Integer value1, Integer value2) {
            addCriterion("answercard_page not between", value1, value2, "answercardPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageIsNull() {
            addCriterion("student_paper_page is null");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageIsNotNull() {
            addCriterion("student_paper_page is not null");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageEqualTo(Integer value) {
            addCriterion("student_paper_page =", value, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageNotEqualTo(Integer value) {
            addCriterion("student_paper_page <>", value, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageGreaterThan(Integer value) {
            addCriterion("student_paper_page >", value, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_paper_page >=", value, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageLessThan(Integer value) {
            addCriterion("student_paper_page <", value, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageLessThanOrEqualTo(Integer value) {
            addCriterion("student_paper_page <=", value, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageIn(List<Integer> values) {
            addCriterion("student_paper_page in", values, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageNotIn(List<Integer> values) {
            addCriterion("student_paper_page not in", values, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageBetween(Integer value1, Integer value2) {
            addCriterion("student_paper_page between", value1, value2, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andStudentPaperPageNotBetween(Integer value1, Integer value2) {
            addCriterion("student_paper_page not between", value1, value2, "studentPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageIsNull() {
            addCriterion("teacher_paper_page is null");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageIsNotNull() {
            addCriterion("teacher_paper_page is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageEqualTo(Integer value) {
            addCriterion("teacher_paper_page =", value, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageNotEqualTo(Integer value) {
            addCriterion("teacher_paper_page <>", value, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageGreaterThan(Integer value) {
            addCriterion("teacher_paper_page >", value, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageGreaterThanOrEqualTo(Integer value) {
            addCriterion("teacher_paper_page >=", value, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageLessThan(Integer value) {
            addCriterion("teacher_paper_page <", value, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageLessThanOrEqualTo(Integer value) {
            addCriterion("teacher_paper_page <=", value, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageIn(List<Integer> values) {
            addCriterion("teacher_paper_page in", values, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageNotIn(List<Integer> values) {
            addCriterion("teacher_paper_page not in", values, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageBetween(Integer value1, Integer value2) {
            addCriterion("teacher_paper_page between", value1, value2, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andTeacherPaperPageNotBetween(Integer value1, Integer value2) {
            addCriterion("teacher_paper_page not between", value1, value2, "teacherPaperPage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageIsNull() {
            addCriterion("package_note_page is null");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageIsNotNull() {
            addCriterion("package_note_page is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageEqualTo(Integer value) {
            addCriterion("package_note_page =", value, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageNotEqualTo(Integer value) {
            addCriterion("package_note_page <>", value, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageGreaterThan(Integer value) {
            addCriterion("package_note_page >", value, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageGreaterThanOrEqualTo(Integer value) {
            addCriterion("package_note_page >=", value, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageLessThan(Integer value) {
            addCriterion("package_note_page <", value, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageLessThanOrEqualTo(Integer value) {
            addCriterion("package_note_page <=", value, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageIn(List<Integer> values) {
            addCriterion("package_note_page in", values, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageNotIn(List<Integer> values) {
            addCriterion("package_note_page not in", values, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageBetween(Integer value1, Integer value2) {
            addCriterion("package_note_page between", value1, value2, "packageNotePage");
            return (Criteria) this;
        }

        public Criteria andPackageNotePageNotBetween(Integer value1, Integer value2) {
            addCriterion("package_note_page not between", value1, value2, "packageNotePage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table generator_card_task_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 15 15:40:35 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}