package com.xcy.mybatis.mo;

import java.io.Serializable;
import java.util.Date;

public class GeneratorCardTaskInfoMo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.display_id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String displayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.create_date
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.generator_type
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer generatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.operator_id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.operator_name
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.send_target
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer sendTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.send_progress
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer sendProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.send_status
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer sendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.generator_status
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer generatorStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.generator_fail_code
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String generatorFailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.generator_fail_message
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String generatorFailMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.file_length
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer fileLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.file_save_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String fileSavePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.test_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String testPaperPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.need_paste_code
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Boolean needPasteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.student_count
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer studentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.unfinished_count
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer unfinishedCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.send_time
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.print_order
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer printOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.need_teacher_paper
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Boolean needTeacherPaper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.original_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String originalPaperPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.test_paper_style
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer testPaperStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.teacher_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private String teacherPaperPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.answercard_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer answercardPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.student_paper_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer studentPaperPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.teacher_paper_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer teacherPaperPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generator_card_task_info.package_note_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private Integer packageNotePage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.id
     *
     * @return the value of generator_card_task_info.id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.id
     *
     * @param id the value for generator_card_task_info.id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.display_id
     *
     * @return the value of generator_card_task_info.display_id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getDisplayId() {
        return displayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.display_id
     *
     * @param displayId the value for generator_card_task_info.display_id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setDisplayId(String displayId) {
        this.displayId = displayId == null ? null : displayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.create_date
     *
     * @return the value of generator_card_task_info.create_date
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.create_date
     *
     * @param createDate the value for generator_card_task_info.create_date
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.generator_type
     *
     * @return the value of generator_card_task_info.generator_type
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getGeneratorType() {
        return generatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.generator_type
     *
     * @param generatorType the value for generator_card_task_info.generator_type
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setGeneratorType(Integer generatorType) {
        this.generatorType = generatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.operator_id
     *
     * @return the value of generator_card_task_info.operator_id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.operator_id
     *
     * @param operatorId the value for generator_card_task_info.operator_id
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.operator_name
     *
     * @return the value of generator_card_task_info.operator_name
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.operator_name
     *
     * @param operatorName the value for generator_card_task_info.operator_name
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.send_target
     *
     * @return the value of generator_card_task_info.send_target
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getSendTarget() {
        return sendTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.send_target
     *
     * @param sendTarget the value for generator_card_task_info.send_target
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setSendTarget(Integer sendTarget) {
        this.sendTarget = sendTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.send_progress
     *
     * @return the value of generator_card_task_info.send_progress
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getSendProgress() {
        return sendProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.send_progress
     *
     * @param sendProgress the value for generator_card_task_info.send_progress
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setSendProgress(Integer sendProgress) {
        this.sendProgress = sendProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.send_status
     *
     * @return the value of generator_card_task_info.send_status
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.send_status
     *
     * @param sendStatus the value for generator_card_task_info.send_status
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setSendStatus(Integer sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.generator_status
     *
     * @return the value of generator_card_task_info.generator_status
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getGeneratorStatus() {
        return generatorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.generator_status
     *
     * @param generatorStatus the value for generator_card_task_info.generator_status
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setGeneratorStatus(Integer generatorStatus) {
        this.generatorStatus = generatorStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.generator_fail_code
     *
     * @return the value of generator_card_task_info.generator_fail_code
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getGeneratorFailCode() {
        return generatorFailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.generator_fail_code
     *
     * @param generatorFailCode the value for generator_card_task_info.generator_fail_code
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setGeneratorFailCode(String generatorFailCode) {
        this.generatorFailCode = generatorFailCode == null ? null : generatorFailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.generator_fail_message
     *
     * @return the value of generator_card_task_info.generator_fail_message
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getGeneratorFailMessage() {
        return generatorFailMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.generator_fail_message
     *
     * @param generatorFailMessage the value for generator_card_task_info.generator_fail_message
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setGeneratorFailMessage(String generatorFailMessage) {
        this.generatorFailMessage = generatorFailMessage == null ? null : generatorFailMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.file_length
     *
     * @return the value of generator_card_task_info.file_length
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getFileLength() {
        return fileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.file_length
     *
     * @param fileLength the value for generator_card_task_info.file_length
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setFileLength(Integer fileLength) {
        this.fileLength = fileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.file_save_path
     *
     * @return the value of generator_card_task_info.file_save_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getFileSavePath() {
        return fileSavePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.file_save_path
     *
     * @param fileSavePath the value for generator_card_task_info.file_save_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setFileSavePath(String fileSavePath) {
        this.fileSavePath = fileSavePath == null ? null : fileSavePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.test_paper_path
     *
     * @return the value of generator_card_task_info.test_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getTestPaperPath() {
        return testPaperPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.test_paper_path
     *
     * @param testPaperPath the value for generator_card_task_info.test_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setTestPaperPath(String testPaperPath) {
        this.testPaperPath = testPaperPath == null ? null : testPaperPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.need_paste_code
     *
     * @return the value of generator_card_task_info.need_paste_code
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Boolean getNeedPasteCode() {
        return needPasteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.need_paste_code
     *
     * @param needPasteCode the value for generator_card_task_info.need_paste_code
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setNeedPasteCode(Boolean needPasteCode) {
        this.needPasteCode = needPasteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.student_count
     *
     * @return the value of generator_card_task_info.student_count
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getStudentCount() {
        return studentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.student_count
     *
     * @param studentCount the value for generator_card_task_info.student_count
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setStudentCount(Integer studentCount) {
        this.studentCount = studentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.unfinished_count
     *
     * @return the value of generator_card_task_info.unfinished_count
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getUnfinishedCount() {
        return unfinishedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.unfinished_count
     *
     * @param unfinishedCount the value for generator_card_task_info.unfinished_count
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setUnfinishedCount(Integer unfinishedCount) {
        this.unfinishedCount = unfinishedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.send_time
     *
     * @return the value of generator_card_task_info.send_time
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.send_time
     *
     * @param sendTime the value for generator_card_task_info.send_time
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.print_order
     *
     * @return the value of generator_card_task_info.print_order
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getPrintOrder() {
        return printOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.print_order
     *
     * @param printOrder the value for generator_card_task_info.print_order
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setPrintOrder(Integer printOrder) {
        this.printOrder = printOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.need_teacher_paper
     *
     * @return the value of generator_card_task_info.need_teacher_paper
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Boolean getNeedTeacherPaper() {
        return needTeacherPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.need_teacher_paper
     *
     * @param needTeacherPaper the value for generator_card_task_info.need_teacher_paper
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setNeedTeacherPaper(Boolean needTeacherPaper) {
        this.needTeacherPaper = needTeacherPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.original_paper_path
     *
     * @return the value of generator_card_task_info.original_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getOriginalPaperPath() {
        return originalPaperPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.original_paper_path
     *
     * @param originalPaperPath the value for generator_card_task_info.original_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setOriginalPaperPath(String originalPaperPath) {
        this.originalPaperPath = originalPaperPath == null ? null : originalPaperPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.test_paper_style
     *
     * @return the value of generator_card_task_info.test_paper_style
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getTestPaperStyle() {
        return testPaperStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.test_paper_style
     *
     * @param testPaperStyle the value for generator_card_task_info.test_paper_style
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setTestPaperStyle(Integer testPaperStyle) {
        this.testPaperStyle = testPaperStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.teacher_paper_path
     *
     * @return the value of generator_card_task_info.teacher_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public String getTeacherPaperPath() {
        return teacherPaperPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.teacher_paper_path
     *
     * @param teacherPaperPath the value for generator_card_task_info.teacher_paper_path
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setTeacherPaperPath(String teacherPaperPath) {
        this.teacherPaperPath = teacherPaperPath == null ? null : teacherPaperPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.answercard_page
     *
     * @return the value of generator_card_task_info.answercard_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getAnswercardPage() {
        return answercardPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.answercard_page
     *
     * @param answercardPage the value for generator_card_task_info.answercard_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setAnswercardPage(Integer answercardPage) {
        this.answercardPage = answercardPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.student_paper_page
     *
     * @return the value of generator_card_task_info.student_paper_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getStudentPaperPage() {
        return studentPaperPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.student_paper_page
     *
     * @param studentPaperPage the value for generator_card_task_info.student_paper_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setStudentPaperPage(Integer studentPaperPage) {
        this.studentPaperPage = studentPaperPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.teacher_paper_page
     *
     * @return the value of generator_card_task_info.teacher_paper_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getTeacherPaperPage() {
        return teacherPaperPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.teacher_paper_page
     *
     * @param teacherPaperPage the value for generator_card_task_info.teacher_paper_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setTeacherPaperPage(Integer teacherPaperPage) {
        this.teacherPaperPage = teacherPaperPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generator_card_task_info.package_note_page
     *
     * @return the value of generator_card_task_info.package_note_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public Integer getPackageNotePage() {
        return packageNotePage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generator_card_task_info.package_note_page
     *
     * @param packageNotePage the value for generator_card_task_info.package_note_page
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    public void setPackageNotePage(Integer packageNotePage) {
        this.packageNotePage = packageNotePage;
    }
}