package com.xcy.mybatis.dao;

import com.xcy.mybatis.mo.GeneratorCardTaskInfoMo;
import com.xcy.mybatis.mo.GeneratorCardTaskInfoMoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface GeneratorCardTaskInfoMoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int countByExample(GeneratorCardTaskInfoMoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int deleteByExample(GeneratorCardTaskInfoMoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int insert(GeneratorCardTaskInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int insertSelective(GeneratorCardTaskInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    List<GeneratorCardTaskInfoMo> selectByExample(GeneratorCardTaskInfoMoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    GeneratorCardTaskInfoMo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") GeneratorCardTaskInfoMo record, @Param("example") GeneratorCardTaskInfoMoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int updateByExample(@Param("record") GeneratorCardTaskInfoMo record, @Param("example") GeneratorCardTaskInfoMoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int updateByPrimaryKeySelective(GeneratorCardTaskInfoMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generator_card_task_info
     *
     * @mbggenerated Mon Oct 15 15:40:35 CST 2018
     */
    int updateByPrimaryKey(GeneratorCardTaskInfoMo record);
}