server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
      repositories:
        enabled: true
#    elasticsearch:
#      cluster-name: cluster_elasticsearch
#      cluster-nodes: localhost:9300,localhost:9301,localhost:9302
#      repositories:
#        enabled: true
  elasticsearch:
    jest:
      uris: http://localhost:9200,http://localhost:9201,http://localhost:9202
      read-timeout: 3000
      connection-timeout: 3000

  datasource:
    url: jdbc:mysql://172.16.10.40:3306/HTgenerator?characterEncoding=utf8
    username: huitongjy
    password: huitongjy123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

rocketmq:
  producer:
    groupName: RocketMQ_Group
    namesrvAddr: localhost:9876
    instanceName: defaultInstance
    ## 4M
    maxMessageSize: 4194304
    ## 10秒
    sendMessageTimeout: 10000
  consumer:
    namesrvAddr: localhost:9876
    groupName: RocketMQ_Group
    topic: TEST
    tag: TEST_2
    consumeThreadMin: 20
    consumeThreadMax: 64

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.xcy.mybatis.mo

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql