
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
      repositories:
        enabled: true
#    elasticsearch:
#      cluster-name: cluster_elasticsearch
#      cluster-nodes: localhost:9300,localhost:9301,localhost:9302
#      repositories:
#        enabled: true
  elasticsearch:
    jest:
      uris: http://localhost:9200,http://localhost:9201,http://localhost:9202
      read-timeout: 3000
      connection-timeout: 3000

rocketmq:
  producer:
    groupName: RocketMQ_Group
    namesrvAddr: localhost:9876
    instanceName: defaultInstance
    ## 4M
    maxMessageSize: 4194304
    ## 10秒
    sendMessageTimeout: 10000
  consumer:
    namesrvAddr: localhost:9876
    groupName: RocketMQ_Group
    topic: TEST
    tag: TEST
    consumeThreadMin: 20
    consumeThreadMax: 64
server:
  port: 8081
